
"use client"

import { initializeApp, getApps, getApp, type FirebaseApp, type FirebaseOptions } from "firebase/app";
import { getFirestore, type Firestore } from "firebase/firestore";
import { getAuth, type Auth } from "firebase/auth";

// This configuration is automatically generated by Firebase Studio.
// Do not edit it manually.
const firebaseConfig: FirebaseOptions = {
  "projectId": "rank-tracker-pro-3000",
  "appId": "1:516533369689:web:a8fd94385ec22a829d2a48",
  "apiKey": "AIzaSyBeA8xRP-fAsUybH14oRaij4UCi40iiG_o",
  "authDomain": "rank-tracker-pro-3000.firebaseapp.com",
  "storageBucket": "rank-tracker-pro-3000.appspot.com",
  "messagingSenderId": "516533369689"
};

let app: FirebaseApp;
let auth: Auth;
let db: Firestore;

if (getApps().length === 0) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

auth = getAuth(app);
db = getFirestore(app);

export { app, db, auth };
