
"use client"

import { initializeApp, getApps, getApp, type FirebaseApp, type FirebaseOptions } from "firebase/app";
import { getFirestore, type Firestore } from "firebase/firestore";
import { getAuth, type Auth } from "firebase/auth";

// This configuration is automatically generated by Firebase Studio.
// Do not edit it manually.
const firebaseConfig: FirebaseOptions = {
  "projectId": "ranktrackerpro-studio",
  "appId": "1:123456789012:web:a1b2c3d4e5f6g7h8i9j0",
  "apiKey": "AIzaSyCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "authDomain": "ranktrackerpro-studio.firebaseapp.com",
  "storageBucket": "ranktrackerpro-studio.appspot.com",
  "messagingSenderId": "123456789012"
};

let app: FirebaseApp;
let auth: Auth;
let db: Firestore;

if (getApps().length === 0) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

auth = getAuth(app);
db = getFirestore(app);

export { app, db, auth };
